import type { Category, Tenant, Amenity, Promotion, SignageSlide } from '@jubilee/shared';

export const SEED_CATEGORIES: Category[] = [
  {
    id: 'c0000000-0000-0000-0000-000000000001',
    slug: 'dine',
    name: 'Dine',
    shortCode: 'FNB',
    description: 'Food, drinks, desserts, fast casual, and family dining concepts',
    icon: 'utensils',
    accentColor: '#EF4444',
    displayOrder: 1,
  },
  {
    id: 'c0000000-0000-0000-0000-000000000002',
    slug: 'learn',
    name: 'Learn',
    shortCode: 'EDU',
    description: 'Enrichment centres, language schools, music, and martial arts academies',
    icon: 'graduation-cap',
    accentColor: '#3B82F6',
    displayOrder: 2,
  },
  {
    id: 'c0000000-0000-0000-0000-000000000003',
    slug: 'relax',
    name: 'Relax',
    shortCode: 'WLN',
    description: 'Hair styling, aesthetics, facial care, and foot reflexology wellness',
    icon: 'sparkles',
    accentColor: '#EC4899',
    displayOrder: 3,
  },
  {
    id: 'c0000000-0000-0000-0000-000000000004',
    slug: 'shop',
    name: 'Shop',
    shortCode: 'RET',
    description: 'Specialty retail, eyecare optometrists, and traditional bridal necessities',
    icon: 'shopping-bag',
    accentColor: '#F59E0B',
    displayOrder: 4,
  },
  {
    id: 'c0000000-0000-0000-0000-000000000005',
    slug: 'services',
    name: 'Services',
    shortCode: 'SVC',
    description: 'Healthcare, traditional Chinese medicine clinics, and community services',
    icon: 'heart-pulse',
    accentColor: '#10B981',
    displayOrder: 5,
  },
];

export const SEED_AMENITIES: Amenity[] = [
  { id: 'a0000000-0000-0000-0000-000000000001', code: 'wheelchair', name: 'Wheelchair Accessible', icon: 'wheelchair', description: 'Full step-free entrance and wide aisles' },
  { id: 'a0000000-0000-0000-0000-000000000002', code: 'halal', name: 'Halal Certified', icon: 'check-circle', description: 'MUIS Halal Certified food establishment' },
  { id: 'a0000000-0000-0000-0000-000000000003', code: 'wifi', name: 'Free Wi-Fi', icon: 'wifi', description: 'High-speed guest internet connection available' },
  { id: 'a0000000-0000-0000-0000-000000000004', code: 'child_friendly', name: 'Child Friendly', icon: 'baby', description: 'Children high chairs, child-safe facilities' },
  { id: 'a0000000-0000-0000-0000-000000000005', code: 'credit_card', name: 'Contactless Payment', icon: 'credit-card', description: 'Accepts PayNow, Nets, Visa, Mastercard, GrabPay' },
  { id: 'a0000000-0000-0000-0000-000000000006', code: 'aircon', name: 'Air Conditioned', icon: 'snowflake', description: 'Fully air-conditioned indoor premises' },
];

const standardHours = [
  { dayOfWeek: 0, dayName: 'Sunday', openTime: '10:00:00', closeTime: '21:30:00', isClosed: false },
  { dayOfWeek: 1, dayName: 'Monday', openTime: '10:00:00', closeTime: '21:30:00', isClosed: false },
  { dayOfWeek: 2, dayName: 'Tuesday', openTime: '10:00:00', closeTime: '21:30:00', isClosed: false },
  { dayOfWeek: 3, dayName: 'Wednesday', openTime: '10:00:00', closeTime: '21:30:00', isClosed: false },
  { dayOfWeek: 4, dayName: 'Thursday', openTime: '10:00:00', closeTime: '21:30:00', isClosed: false },
  { dayOfWeek: 5, dayName: 'Friday', openTime: '10:00:00', closeTime: '21:30:00', isClosed: false },
  { dayOfWeek: 6, dayName: 'Saturday', openTime: '10:00:00', closeTime: '21:30:00', isClosed: false },
];

export const SEED_TENANTS: Tenant[] = [
  // DINE (6)
  {
    id: 't0000000-0000-0000-0000-000000000001',
    categoryId: 'c0000000-0000-0000-0000-000000000001',
    categorySlug: 'dine',
    categoryName: 'Dine',
    categoryColor: '#EF4444',
    slug: 'bantianyao-grilled-fish',
    name: 'BANTIANYAO GRILLED FISH',
    floorLevel: 'L2',
    unitNumber: '#02-01/02',
    summary: 'Renowned Chinese catering brand famous for rattan pepper grilled fish and over 1,500 outlets across Asia.',
    description: 'Bantianyao Grilled Fish brings authentic Sichuan flavors to Ang Mo Kio. Specializing in fresh whole fish simmered in rich signature broths including rattan pepper, spicy mala, fresh garlic, and tomato broth. Includes free-flow rice, drinks, and ice cream counter.',
    phone: '+65 6451 2388',
    whatsapp: '+65 9123 4567',
    email: 'amk@bantianyao.sg',
    website: 'https://bantianyao.sg',
    logoUrl: '/images/tenants/bantianyao-logo.png',
    heroImageUrl: '/images/tenants/bantianyao-hero.jpg',
    gallery: ['/images/tenants/bantianyao-1.jpg', '/images/tenants/bantianyao-2.jpg'],
    socialLinks: { facebook: 'https://facebook.com/bantianyaosg' },
    tags: ['grilled fish', 'sichuan', 'mala', 'family dining', 'chinese'],
    metadata: { cuisine: 'Sichuan / Chinese', price_range: '$$', seating_capacity: 90, halal: false },
    isActive: true,
    isFeatured: true,
    displayOrder: 1,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[2], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },
  {
    id: 't0000000-0000-0000-0000-000000000002',
    categoryId: 'c0000000-0000-0000-0000-000000000001',
    categorySlug: 'dine',
    categoryName: 'Dine',
    categoryColor: '#EF4444',
    slug: 'jolly-desserts',
    name: 'Jolly Desserts',
    floorLevel: 'L1',
    unitNumber: '#01-11',
    summary: 'Traditional Chinese tong shui, shaved ice desserts, and artisanal sweet snacks.',
    description: 'Jolly Desserts offers comforting traditional sweet soups and modern shaved ice creations. Popular favorites include Mango Pomelo Sago, Peach Gum Herbal Broth, Tang Yuan ginger soup, and Durian shaved snow ice.',
    phone: '+65 6452 8812',
    whatsapp: '+65 9876 5432',
    email: 'hello@jollydesserts.com',
    website: 'https://jollydesserts.com',
    logoUrl: '/images/tenants/jolly-logo.png',
    heroImageUrl: '/images/tenants/jolly-hero.jpg',
    gallery: [],
    socialLinks: {},
    tags: ['dessert', 'tong shui', 'shaved ice', 'mango pomelo', 'sweets'],
    metadata: { cuisine: 'Desserts', price_range: '$', seating_capacity: 30, takeaway: true },
    isActive: true,
    isFeatured: false,
    displayOrder: 2,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },
  {
    id: 't0000000-0000-0000-0000-000000000003',
    categoryId: 'c0000000-0000-0000-0000-000000000001',
    categorySlug: 'dine',
    categoryName: 'Dine',
    categoryColor: '#EF4444',
    slug: 'max-see-veggie-house',
    name: 'Max-See & Veggie House',
    floorLevel: 'L1',
    unitNumber: '#01-08',
    summary: 'Plant-based delicacies, fresh fruit teas, bubble tea, and vegetarian dining.',
    description: 'Combining a specialized vegetarian cafe with refreshing handcrafted teas. Offers plant-based bento boxes, vegetarian laksa, herbal noodle bowls alongside fresh fruit teas, cheese foam teas, and brown sugar boba.',
    phone: '+65 6453 9921',
    whatsapp: '+65 9234 5678',
    email: 'enquiry@maxsee.sg',
    website: 'https://maxsee.sg',
    logoUrl: '/images/tenants/maxsee-logo.png',
    heroImageUrl: '/images/tenants/maxsee-hero.jpg',
    gallery: [],
    socialLinks: {},
    tags: ['vegetarian', 'bubble tea', 'fruit tea', 'plant based', 'cafe'],
    metadata: { cuisine: 'Vegetarian & Beverages', price_range: '$', seating_capacity: 25, takeaway: true },
    isActive: true,
    isFeatured: false,
    displayOrder: 3,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },
  {
    id: 't0000000-0000-0000-0000-000000000004',
    categoryId: 'c0000000-0000-0000-0000-000000000001',
    categorySlug: 'dine',
    categoryName: 'Dine',
    categoryColor: '#EF4444',
    slug: 'siam-square-mookata',
    name: 'Siam Square Mookata',
    floorLevel: 'L2',
    unitNumber: '#02-03',
    summary: 'Popular casual Thai mookata BBQ and steamboat with authentic chili dips.',
    description: 'Siam Square Mookata serves sizzling Thai street BBQ and hotpot. Freshly marinated meats, seafood, cheese dip, and their signature 3 levels of chili sauce. Great for friends and family gatherings.',
    phone: '+65 6454 1109',
    whatsapp: '+65 9345 6789',
    email: 'contact@siamsquaremookata.com.sg',
    website: 'https://siamsquaremookata.com.sg',
    logoUrl: '/images/tenants/siamsquare-logo.png',
    heroImageUrl: '/images/tenants/siamsquare-hero.jpg',
    gallery: [],
    socialLinks: { facebook: 'https://facebook.com/siamsquaremookata' },
    tags: ['thai', 'mookata', 'bbq', 'hotpot', 'buffet'],
    metadata: { cuisine: 'Thai BBQ', price_range: '$$', seating_capacity: 80, halal: false },
    isActive: true,
    isFeatured: true,
    displayOrder: 4,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },
  {
    id: 't0000000-0000-0000-0000-000000000005',
    categoryId: 'c0000000-0000-0000-0000-000000000001',
    categorySlug: 'dine',
    categoryName: 'Dine',
    categoryColor: '#EF4444',
    slug: 'subway',
    name: 'Subway',
    floorLevel: 'L1',
    unitNumber: '#01-05',
    summary: 'Freshly made submarine sandwiches, wraps, salads, and cookies.',
    description: 'The world-famous fast casual brand serving wholesome customized submarine sandwiches, wraps, and salads made fresh in front of you. Choose your fresh baked bread, crisp vegetables, protein, and savory sauces.',
    phone: '+65 6455 7733',
    whatsapp: '+65 9456 7890',
    email: 'jubilee@subway.com.sg',
    website: 'https://subway.com.sg',
    logoUrl: '/images/tenants/subway-logo.png',
    heroImageUrl: '/images/tenants/subway-hero.jpg',
    gallery: [],
    socialLinks: {},
    tags: ['sandwiches', 'halal', 'fast food', 'healthy', 'takeaway'],
    metadata: { cuisine: 'Fast Casual', price_range: '$', seating_capacity: 40, halal: true },
    isActive: true,
    isFeatured: false,
    displayOrder: 5,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[1], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },
  {
    id: 't0000000-0000-0000-0000-000000000006',
    categoryId: 'c0000000-0000-0000-0000-000000000001',
    categorySlug: 'dine',
    categoryName: 'Dine',
    categoryColor: '#EF4444',
    slug: 'ya-kun-kaya-toast',
    name: 'Ya Kun Kaya Toast',
    floorLevel: 'L1',
    unitNumber: '#01-01/02',
    summary: 'Traditional Singapore kaya toast, soft-boiled eggs, and aromatic Nanyang kopi/teh.',
    description: 'Singapore heritage coffeehouse icon since 1944. Crispy grilled toast lathered with aromatic kaya and butter, runny soft-boiled eggs with dark soya sauce and pepper, paired with robust freshly brewed Nanyang kopi.',
    phone: '+65 6456 0088',
    whatsapp: '+65 9567 8901',
    email: 'customerservice@yakun.com',
    website: 'https://yakun.com',
    logoUrl: '/images/tenants/yakun-logo.png',
    heroImageUrl: '/images/tenants/yakun-hero.jpg',
    gallery: [],
    socialLinks: { facebook: 'https://facebook.com/yakunkatoast' },
    tags: ['kaya toast', 'kopi', 'heritage', 'breakfast', 'singaporean'],
    metadata: { cuisine: 'Singapore Traditional Coffeehouse', price_range: '$', seating_capacity: 55, halal: false },
    isActive: true,
    isFeatured: true,
    displayOrder: 6,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[2], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },

  // LEARN (9)
  {
    id: 't0000000-0000-0000-0000-000000000007',
    categoryId: 'c0000000-0000-0000-0000-000000000002',
    categorySlug: 'learn',
    categoryName: 'Learn',
    categoryColor: '#3B82F6',
    slug: 'agrader-learning-centre',
    name: 'AGrader Learning Centre',
    floorLevel: 'L3',
    unitNumber: '#03-01/02',
    summary: 'Primary & Secondary tuition programmes with comprehensive worksheets and diagnostic assessments.',
    description: 'Award-winning academic tuition centre in Singapore for Primary and Secondary English, Math, Science, and Creative Writing. Includes proprietary EverLoop Revision system and homework clinic assistance.',
    phone: '+65 6457 1234',
    whatsapp: '+65 9678 9012',
    email: 'amk@agrader.sg',
    website: 'https://agrader.sg',
    logoUrl: '/images/tenants/agrader-logo.png',
    heroImageUrl: '/images/tenants/agrader-hero.jpg',
    gallery: [],
    socialLinks: {},
    tags: ['tuition', 'primary', 'secondary', 'math', 'science', 'english'],
    metadata: { levels: ['Primary 1-6', 'Secondary 1-4'], subjects: ['English', 'Math', 'Science', 'Creative Writing'] },
    isActive: true,
    isFeatured: true,
    displayOrder: 7,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[3], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },
  {
    id: 't0000000-0000-0000-0000-000000000008',
    categoryId: 'c0000000-0000-0000-0000-000000000002',
    categorySlug: 'learn',
    categoryName: 'Learn',
    categoryColor: '#3B82F6',
    slug: 'artlette',
    name: 'Artlette',
    floorLevel: 'L3',
    unitNumber: '#03-05',
    summary: 'Creative art studio offering drawing, painting, acrylic, and portfolio preparation for kids and teens.',
    description: 'Artlette creates an imaginative art space for children and teens to explore watercolors, acrylic canvas painting, clay modeling, digital illustration, and DSA art portfolio guidance.',
    phone: '+65 6458 5678',
    whatsapp: '+65 9789 0123',
    email: 'hello@artlette.sg',
    website: 'https://artlette.sg',
    logoUrl: '/images/tenants/artlette-logo.png',
    heroImageUrl: '/images/tenants/artlette-hero.jpg',
    gallery: [],
    socialLinks: {},
    tags: ['art', 'drawing', 'painting', 'acrylic', 'dsa portfolio', 'kids'],
    metadata: { age_group: 'Ages 4 to 18', programmes: ['Children Art', 'Teens Art Studio', 'DSA Art Portfolio'] },
    isActive: true,
    isFeatured: false,
    displayOrder: 8,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[3], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },
  {
    id: 't0000000-0000-0000-0000-000000000009',
    categoryId: 'c0000000-0000-0000-0000-000000000002',
    categorySlug: 'learn',
    categoryName: 'Learn',
    categoryColor: '#3B82F6',
    slug: 'guitar-emerge-music-school',
    name: 'Guitar Emerge Music School',
    floorLevel: 'L4',
    unitNumber: '#04-03',
    summary: 'Acoustic, electric, and bass guitar lessons tailored for leisure and graded examinations.',
    description: 'Specialized guitar boutique school offering individual and small-group coaching in Acoustic Guitar, Electric Guitar, Classical, Bass, and Ukulele for students of all ages.',
    phone: '+65 6459 9012',
    whatsapp: '+65 9890 1234',
    email: 'info@guitaremerge.com',
    website: 'https://guitaremerge.com',
    logoUrl: '/images/tenants/guitaremerge-logo.png',
    heroImageUrl: '/images/tenants/guitaremerge-hero.jpg',
    gallery: [],
    socialLinks: {},
    tags: ['guitar', 'music school', 'acoustic', 'electric guitar', 'ukulele', 'graded exams'],
    metadata: { instruments: ['Acoustic Guitar', 'Electric Guitar', 'Bass', 'Ukulele'], certification: 'Rockschool / Trinity' },
    isActive: true,
    isFeatured: false,
    displayOrder: 9,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },
  {
    id: 't0000000-0000-0000-0000-000000000010',
    categoryId: 'c0000000-0000-0000-0000-000000000002',
    categorySlug: 'learn',
    categoryName: 'Learn',
    categoryColor: '#3B82F6',
    slug: 'jeong-in-taekwondo',
    name: 'Jeong-In Taekwondo Education Centre',
    floorLevel: 'L3',
    unitNumber: '#03-08/09',
    summary: 'Authentic Korean Taekwondo academy focusing on discipline, poomsae, sparring, and belt advancement.',
    description: 'Led by Kukkiwon-certified Korean Grandmasters and coaches. Teaches traditional Korean martial arts values, self-defense, Olympic sparring, and character development for tots, children, and adults.',
    phone: '+65 6460 3456',
    whatsapp: '+65 9901 2345',
    email: 'amk@jeongintaekwondo.com',
    website: 'https://jeongintaekwondo.com',
    logoUrl: '/images/tenants/jeongin-logo.png',
    heroImageUrl: '/images/tenants/jeongin-hero.jpg',
    gallery: [],
    socialLinks: {},
    tags: ['taekwondo', 'martial arts', 'korean', 'self defense', 'character building'],
    metadata: { certification: 'Kukkiwon / Singapore Taekwondo Federation', age_group: 'Ages 3.5 and above' },
    isActive: true,
    isFeatured: true,
    displayOrder: 10,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[3], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },
  {
    id: 't0000000-0000-0000-0000-000000000011',
    categoryId: 'c0000000-0000-0000-0000-000000000002',
    categorySlug: 'learn',
    categoryName: 'Learn',
    categoryColor: '#3B82F6',
    slug: 'lcentral',
    name: 'LCentral',
    floorLevel: 'L3',
    unitNumber: '#03-06/07',
    summary: 'Structured early-reading, phonics, grammar, speech, and PSLE English mastery courses.',
    description: 'Premier English language enrichment specialist in Singapore. Offers phonics foundation, reading fluency, advanced grammar, primary writing composition, and speech communication.',
    phone: '+65 6461 7890',
    whatsapp: '+65 9012 3456',
    email: 'amk@lcentral.net',
    website: 'https://lcentral.net',
    logoUrl: '/images/tenants/lcentral-logo.png',
    heroImageUrl: '/images/tenants/lcentral-hero.jpg',
    gallery: [],
    socialLinks: {},
    tags: ['english', 'phonics', 'reading', 'psle english', 'literacy'],
    metadata: { programmes: ['LaunchPad (Phonics)', 'LiftOff (Reading)', 'Success (Primary English)'] },
    isActive: true,
    isFeatured: false,
    displayOrder: 11,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[3], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },
  {
    id: 't0000000-0000-0000-0000-000000000012',
    categoryId: 'c0000000-0000-0000-0000-000000000002',
    categorySlug: 'learn',
    categoryName: 'Learn',
    categoryColor: '#3B82F6',
    slug: 'learning-kidz',
    name: 'Learning Kidz',
    floorLevel: 'L4',
    unitNumber: '#04-01/02',
    summary: 'Holistic early childhood curriculum focusing on cognitive and motor skill development.',
    description: 'Warm, nurturing early learning preschool environment encouraging inquiry-based learning, social socialization, bilingual literacy, music movement, and STEM discovery for infants and preschoolers.',
    phone: '+65 6462 2345',
    whatsapp: '+65 9123 7890',
    email: 'enquiry@learningkidz.com.sg',
    website: 'https://learningkidz.com.sg',
    logoUrl: '/images/tenants/learningkidz-logo.png',
    heroImageUrl: '/images/tenants/learningkidz-hero.jpg',
    gallery: [],
    socialLinks: {},
    tags: ['preschool', 'childcare', 'early learning', 'kindergarten', 'toddler'],
    metadata: { levels: ['Playgroup', 'Nursery 1-2', 'Kindergarten 1-2'], ecda_licensed: true },
    isActive: true,
    isFeatured: false,
    displayOrder: 12,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[3], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },
  {
    id: 't0000000-0000-0000-0000-000000000013',
    categoryId: 'c0000000-0000-0000-0000-000000000002',
    categorySlug: 'learn',
    categoryName: 'Learn',
    categoryColor: '#3B82F6',
    slug: 'mcube-learning-centre',
    name: 'Mcube Learning Centre',
    floorLevel: 'L3',
    unitNumber: '#03-03/04',
    summary: 'Olympiad math, heuristic problem solving, and secondary math coaching.',
    description: 'Math specialists dedicated to transforming how students understand and conquer math. Teaches model-drawing heuristics, algebra manipulation, exam problem-solving speed, and Olympiad competition prep.',
    phone: '+65 6463 6789',
    whatsapp: '+65 9234 8901',
    email: 'info@mcubelearning.sg',
    website: 'https://mcubelearning.sg',
    logoUrl: '/images/tenants/mcube-logo.png',
    heroImageUrl: '/images/tenants/mcube-hero.jpg',
    gallery: [],
    socialLinks: {},
    tags: ['math', 'olympiad math', 'heuristics', 'psle math', 'o level math'],
    metadata: { subjects: ['Primary Heuristics Math', 'Secondary E-Math / A-Math', 'Math Olympiad'] },
    isActive: true,
    isFeatured: false,
    displayOrder: 13,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[3], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },
  {
    id: 't0000000-0000-0000-0000-000000000014',
    categoryId: 'c0000000-0000-0000-0000-000000000002',
    categorySlug: 'learn',
    categoryName: 'Learn',
    categoryColor: '#3B82F6',
    slug: 'my-drum-school',
    name: 'My Drum School',
    floorLevel: 'L4',
    unitNumber: '#04-04/05',
    summary: 'Specialized drum education with modern facilities, certified instructors, and customized syllabi.',
    description: 'Singapore premier drum-only music academy. Equipped with state-of-the-art acoustic drum studios, customized digital tracking syllabus, Rockschool examination certification, and live performance opportunities.',
    phone: '+65 6464 0123',
    whatsapp: '+65 9345 9012',
    email: 'amk@mydrumschool.com',
    website: 'https://mydrumschool.com',
    logoUrl: '/images/tenants/mydrumschool-logo.png',
    heroImageUrl: '/images/tenants/mydrumschool-hero.jpg',
    gallery: ['/images/tenants/mds-1.jpg', '/images/tenants/mds-2.jpg'],
    socialLinks: { instagram: 'https://instagram.com/mydrumschool', youtube: 'https://youtube.com/mydrumschool' },
    tags: ['drums', 'percussion', 'music school', 'rockschool', 'drum lessons'],
    metadata: { facility: 'Acoustic Soundproof Studios', curriculum: 'MDS Proprietary Drum Syllabus', exam_board: 'Rockschool UK' },
    isActive: true,
    isFeatured: true,
    displayOrder: 14,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[2], SEED_AMENITIES[3], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },
  {
    id: 't0000000-0000-0000-0000-000000000015',
    categoryId: 'c0000000-0000-0000-0000-000000000002',
    categorySlug: 'learn',
    categoryName: 'Learn',
    categoryColor: '#3B82F6',
    slug: 'wang-learning-centre',
    name: 'Wang Learning Centre',
    floorLevel: 'L3',
    unitNumber: '#03-10/11',
    summary: 'High-impact Chinese language tuition, creative writing, and oral exam preparation.',
    description: 'One of Singapore most respected Chinese language tuition brands. Focuses on Primary and Secondary Chinese composition writing, comprehension skills, Hanyu Pinyin mastery, and oral examination confidence.',
    phone: '+65 6465 4567',
    whatsapp: '+65 9456 0123',
    email: 'amk@wang.com.sg',
    website: 'https://wang.com.sg',
    logoUrl: '/images/tenants/wang-logo.png',
    heroImageUrl: '/images/tenants/wang-hero.jpg',
    gallery: [],
    socialLinks: {},
    tags: ['chinese tuition', 'composition', 'hanyu pinyin', 'psle chinese', 'o level higher chinese'],
    metadata: { subjects: ['Primary Chinese', 'Higher Chinese', 'Secondary Chinese', 'Oral & Composition'] },
    isActive: true,
    isFeatured: true,
    displayOrder: 15,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[3], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },

  // RELAX (5)
  {
    id: 't0000000-0000-0000-0000-000000000016',
    categoryId: 'c0000000-0000-0000-0000-000000000003',
    categorySlug: 'relax',
    categoryName: 'Relax',
    categoryColor: '#EC4899',
    slug: '7-studio-hair-salon',
    name: '7 Studio Hair Salon',
    floorLevel: 'L2',
    unitNumber: '#02-06',
    summary: 'Professional haircuts, coloring, perm treatments, and scalp therapy.',
    description: 'Full-service hair design salon specializing in modern Korean perms, Japanese rebonding, balayage hair coloring, and detoxifying scalp treatments using premium haircare formulations.',
    phone: '+65 6466 8901',
    whatsapp: '+65 9567 1234',
    email: 'booking@7studio.sg',
    website: 'https://7studio.sg',
    logoUrl: '/images/tenants/7studio-logo.png',
    heroImageUrl: '/images/tenants/7studio-hero.jpg',
    gallery: [],
    socialLinks: {},
    tags: ['hair salon', 'korean perm', 'haircut', 'coloring', 'scalp treatment'],
    metadata: { services: ['Cut & Blow', 'Korean C-Curl Perm', 'Scalp Therapy', 'Balayage Color'] },
    isActive: true,
    isFeatured: false,
    displayOrder: 16,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },
  {
    id: 't0000000-0000-0000-0000-000000000017',
    categoryId: 'c0000000-0000-0000-0000-000000000003',
    categorySlug: 'relax',
    categoryName: 'Relax',
    categoryColor: '#EC4899',
    slug: 'ashi-foot-reflexology',
    name: 'Ashi Foot Reflexology',
    floorLevel: 'L2',
    unitNumber: '#02-08',
    summary: 'Traditional foot reflexology, acupressure body massage, and tension relief therapy.',
    description: 'Serene wellness sanctuary providing authentic pressure-point foot reflexology, back & shoulder pain relief massage, and herbal foot soaks to rejuvenate tired bodies and promote blood circulation.',
    phone: '+65 6467 2345',
    whatsapp: '+65 9678 2345',
    email: 'info@ashireflexology.com',
    website: 'https://ashireflexology.com',
    logoUrl: '/images/tenants/ashi-logo.png',
    heroImageUrl: '/images/tenants/ashi-hero.jpg',
    gallery: [],
    socialLinks: {},
    tags: ['massage', 'foot reflexology', 'wellness', 'acupressure', 'relaxation'],
    metadata: { services: ['Foot Reflexology (40/60 min)', 'Full Body Acupressure', 'Shoulder & Neck Relief'] },
    isActive: true,
    isFeatured: true,
    displayOrder: 17,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },
  {
    id: 't0000000-0000-0000-0000-000000000018',
    categoryId: 'c0000000-0000-0000-0000-000000000003',
    categorySlug: 'relax',
    categoryName: 'Relax',
    categoryColor: '#EC4899',
    slug: 'glow-haven',
    name: 'Glow Haven',
    floorLevel: 'L2',
    unitNumber: '#02-09',
    summary: 'Personalized facial treatments, anti-aging therapies, and deep-cleansing skin regimens.',
    description: 'Boutique facial and skincare studio providing bespoke customized facial therapies, extraction treatments, collagen plumping, and LED light skin rejuvenation in private, tranquil suites.',
    phone: '+65 6468 6789',
    whatsapp: '+65 9789 3456',
    email: 'amk@glowhaven.sg',
    website: 'https://glowhaven.sg',
    logoUrl: '/images/tenants/glowhaven-logo.png',
    heroImageUrl: '/images/tenants/glowhaven-hero.jpg',
    gallery: [],
    socialLinks: {},
    tags: ['facial', 'skincare', 'anti aging', 'extraction', 'beauty'],
    metadata: { services: ['Deep Pore Cleansing', 'Hydra Glow Facial', 'Oxygen Infusion'] },
    isActive: true,
    isFeatured: false,
    displayOrder: 18,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },
  {
    id: 't0000000-0000-0000-0000-000000000019',
    categoryId: 'c0000000-0000-0000-0000-000000000003',
    categorySlug: 'relax',
    categoryName: 'Relax',
    categoryColor: '#EC4899',
    slug: 'skin-labo',
    name: 'Skin Labo',
    floorLevel: 'L2',
    unitNumber: '#02-04/05',
    summary: 'Advanced non-invasive skin treatments and aesthetic beauty care.',
    description: 'Medical-grade aesthetic skincare centre offering HIFU lifting, radio-frequency skin tightening, pigment laser therapy, and soothing botanical skin treatments.',
    phone: '+65 6469 0123',
    whatsapp: '+65 9890 4567',
    email: 'enquiry@skinlabo.com.sg',
    website: 'https://skinlabo.com.sg',
    logoUrl: '/images/tenants/skinlabo-logo.png',
    heroImageUrl: '/images/tenants/skinlabo-hero.jpg',
    gallery: [],
    socialLinks: {},
    tags: ['aesthetics', 'hifu', 'skin tightening', 'pigmentation', 'beauty care'],
    metadata: { services: ['HIFU Face Lift', 'Pico Laser Glow', 'RF Skin Tightening'] },
    isActive: true,
    isFeatured: false,
    displayOrder: 19,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },
  {
    id: 't0000000-0000-0000-0000-000000000020',
    categoryId: 'c0000000-0000-0000-0000-000000000003',
    categorySlug: 'relax',
    categoryName: 'Relax',
    categoryColor: '#EC4899',
    slug: 'soul-scissors-studio',
    name: 'Soul Scissors Studio',
    floorLevel: 'L2',
    unitNumber: '#02-07',
    summary: 'Trend haircuts, creative dye work, and modern hair styling.',
    description: 'Trendy hair salon known for creative color transformations, fashion hair highlights, precision fade cuts, and nourishing Olaplex hair bond repair treatments.',
    phone: '+65 6470 4567',
    whatsapp: '+65 9901 5678',
    email: 'contact@soulscissors.com',
    website: 'https://soulscissors.com',
    logoUrl: '/images/tenants/soulscissors-logo.png',
    heroImageUrl: '/images/tenants/soulscissors-hero.jpg',
    gallery: [],
    socialLinks: {},
    tags: ['hair salon', 'creative color', 'fade cut', 'olaplex', 'styling'],
    metadata: { services: ['Precision Cuts', 'Ombre / Highlights', 'Olaplex Treatment'] },
    isActive: true,
    isFeatured: false,
    displayOrder: 20,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },

  // SHOP (2)
  {
    id: 't0000000-0000-0000-0000-000000000021',
    categoryId: 'c0000000-0000-0000-0000-000000000004',
    categorySlug: 'shop',
    categoryName: 'Shop',
    categoryColor: '#F59E0B',
    slug: 'eyechamp-optometrists',
    name: 'Eyechamp Optometrists',
    floorLevel: 'L1',
    unitNumber: '#01-06/07',
    summary: 'Comprehensive eye examinations, designer frames, prescription lenses, and contact lenses.',
    description: 'Full-scope optical practice staffed by certified optometrists. Offers computerized vision testing, orthokeratology, myopia control lenses, designer sunglasses, and premium spectacle frames.',
    phone: '+65 6471 8901',
    whatsapp: '+65 9012 6789',
    email: 'amk@eyechamp.com.sg',
    website: 'https://eyechamp.com.sg',
    logoUrl: '/images/tenants/eyechamp-logo.png',
    heroImageUrl: '/images/tenants/eyechamp-hero.jpg',
    gallery: [],
    socialLinks: {},
    tags: ['optical', 'optometry', 'glasses', 'spectacles', 'contact lenses', 'myopia control'],
    metadata: { brands: ['Ray-Ban', 'Gucci', 'Hoya', 'Essilor', 'Acuvue'], services: ['Eye Health Check', 'Myopia Control Clinic'] },
    isActive: true,
    isFeatured: true,
    displayOrder: 21,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },
  {
    id: 't0000000-0000-0000-0000-000000000022',
    categoryId: 'c0000000-0000-0000-0000-000000000004',
    categorySlug: 'shop',
    categoryName: 'Shop',
    categoryColor: '#F59E0B',
    slug: 'the-chinese-wedding-shop',
    name: 'The Chinese Wedding Shop',
    floorLevel: 'L1',
    unitNumber: '#01-09/10',
    summary: 'Chinese betrothal sets (Guo Da Li), dowry packages, wedding decorations, and traditional bridal necessities.',
    description: 'Singapore leading specialty bridal customs purveyor. Dedicated to preserving Chinese wedding heritage with curated Guo Da Li gift baskets, traditional bedding, tea ceremony tea sets, and dialect wedding consultation.',
    phone: '+65 6472 2345',
    whatsapp: '+65 9123 0123',
    email: 'amk@thechineseweddingshop.com.sg',
    website: 'https://thechineseweddingshop.com.sg',
    logoUrl: '/images/tenants/chinesewedding-logo.png',
    heroImageUrl: '/images/tenants/chinesewedding-hero.jpg',
    gallery: [],
    socialLinks: {},
    tags: ['chinese wedding', 'guo da li', 'betrothal', 'dowry', 'traditional bridal'],
    metadata: { specialties: ['Dialect Custom Consultation', 'Guo Da Li Hampers', 'Tea Ceremony Sets'] },
    isActive: true,
    isFeatured: false,
    displayOrder: 22,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },

  // SERVICES (1)
  {
    id: 't0000000-0000-0000-0000-000000000023',
    categoryId: 'c0000000-0000-0000-0000-000000000005',
    categorySlug: 'services',
    categoryName: 'Services',
    categoryColor: '#10B981',
    slug: 'tianyi-inmed-tcm-clinic',
    name: 'Tianyi InMed TCM Clinic',
    floorLevel: 'L1',
    unitNumber: '#01-03/04',
    summary: 'Certified TCM physicians providing acupuncture, cupping, herbal medicine, and pain management therapy.',
    description: 'Registered TCM clinic offering holistic clinical diagnoses, painless acupuncture, therapeutic cupping (Ba Guan), Tuina manipulation, and customized herbal granule prescriptions for chronic ailments and wellness.',
    phone: '+65 6473 6789',
    whatsapp: '+65 9234 1234',
    email: 'clinic@tianyitcm.com.sg',
    website: 'https://tianyitcm.com.sg',
    logoUrl: '/images/tenants/tianyi-logo.png',
    heroImageUrl: '/images/tenants/tianyi-hero.jpg',
    gallery: [],
    socialLinks: {},
    tags: ['tcm', 'acupuncture', 'cupping', 'herbal medicine', 'tuina', 'healthcare'],
    metadata: { certifications: ['TCMPB Registered Physicians', 'CHAS Approved'], services: ['Acupuncture', 'Herbal Prescription', 'Cupping Therapy', 'Tuina'] },
    isActive: true,
    isFeatured: true,
    displayOrder: 23,
    operatingHours: standardHours,
    amenities: [SEED_AMENITIES[0], SEED_AMENITIES[4], SEED_AMENITIES[5]],
  },
];

export const SEED_PROMOTIONS: Promotion[] = [
  {
    id: 'p0000000-0000-0000-0000-000000000001',
    tenantId: 't0000000-0000-0000-0000-000000000001',
    tenantName: 'BANTIANYAO GRILLED FISH',
    tenantSlug: 'bantianyao-grilled-fish',
    title: 'Bantianyao Weekday Lunch Special — 20% Off Whole Fish',
    slug: 'bantianyao-lunch-special',
    summary: 'Enjoy 20% off all whole grilled fish flavors between 11:30am and 3:00pm on weekdays.',
    description: 'Valid for dine-in only from Monday to Friday. Choice of rattan pepper, fresh tomato, or mala broth.',
    bannerUrl: '/images/promotions/promo-bantianyao.jpg',
    badgeText: '20% OFF',
    termsConditions: 'Valid on weekdays only excluding Public Holidays. Not valid with other bank promos.',
    startDate: '2026-09-01',
    endDate: '2026-10-31',
    isActive: true,
    isFeatured: true,
    displayOrder: 1,
  },
  {
    id: 'p0000000-0000-0000-0000-000000000002',
    tenantId: 't0000000-0000-0000-0000-000000000014',
    tenantName: 'My Drum School',
    tenantSlug: 'my-drum-school',
    title: 'My Drum School Free 30-Minute Trial Session',
    slug: 'mds-free-trial',
    summary: 'Book a complimentary 1-on-1 acoustic drum evaluation and studio tour.',
    description: 'Experience hands-on drum coaching with certified music tutors at Level 4.',
    bannerUrl: '/images/promotions/promo-drum.jpg',
    badgeText: 'FREE TRIAL',
    termsConditions: 'Limited to 1 redemption per new student.',
    startDate: '2026-09-01',
    endDate: '2026-12-31',
    isActive: true,
    isFeatured: true,
    displayOrder: 2,
  },
  {
    id: 'p0000000-0000-0000-0000-000000000017',
    tenantId: 't0000000-0000-0000-0000-000000000017',
    tenantName: 'Ashi Foot Reflexology',
    tenantSlug: 'ashi-foot-reflexology',
    title: 'Ashi Reflexology: 60-min Foot & Shoulder Combo at $58',
    slug: 'ashi-wellness-combo',
    summary: 'Relax and relieve weekday fatigue with our signature acupressure package.',
    description: 'Includes 40 mins foot reflexology + 20 mins neck & shoulder tension relief massage.',
    bannerUrl: '/images/promotions/promo-ashi.jpg',
    badgeText: '$58 ONLY',
    termsConditions: 'Valid daily before 5:00pm.',
    startDate: '2026-09-01',
    endDate: '2026-11-30',
    isActive: true,
    isFeatured: false,
    displayOrder: 3,
  },
];

export const SEED_SIGNAGE_SLIDES: SignageSlide[] = [
  {
    id: 's0000000-0000-0000-0000-000000000001',
    title: 'Welcome to Jubilee Square AMK',
    slideType: 'image',
    mediaUrl: '/images/signage/welcome-banner.jpg',
    durationSeconds: 12,
    targetLocations: ['all'],
    tenantId: null,
    tenant: null,
    headline: 'Welcome to Jubilee Square',
    subheadline: 'Your Community Dining, Learning & Wellness Destination in AMK',
    isActive: true,
    priority: 1,
  },
  {
    id: 's0000000-0000-0000-0000-000000000002',
    title: 'Level 3 & 4 Education Hub Spotlight',
    slideType: 'image',
    mediaUrl: '/images/signage/education-spotlight.jpg',
    durationSeconds: 15,
    targetLocations: ['L1_lift', 'L1_counter', 'L3_lift', 'L4_lift'],
    tenantId: null,
    tenant: null,
    headline: 'Explore Top Enrichment Centres on Levels 3 & 4',
    subheadline: 'My Drum School • AGrader • LCentral • Jeong-In Taekwondo • Wang Learning',
    isActive: true,
    priority: 2,
  },
  {
    id: 's0000000-0000-0000-0000-000000000003',
    title: 'Bantianyao Grilled Fish Featured',
    slideType: 'image',
    mediaUrl: '/images/signage/bantianyao-slide.jpg',
    durationSeconds: 10,
    targetLocations: ['L1_counter', 'L2_lift', 'L2_escalator'],
    tenantId: 't0000000-0000-0000-0000-000000000001',
    tenant: {
      name: 'BANTIANYAO GRILLED FISH',
      slug: 'bantianyao-grilled-fish',
      unitNumber: '#02-01/02',
      floorLevel: 'L2',
    },
    headline: 'Sizzling Sichuan Flavors on Level 2 (#02-01)',
    subheadline: 'Rattan Pepper Grilled Fish & Unlimited Buffet Counter',
    isActive: true,
    priority: 3,
  },
  {
    id: 's0000000-0000-0000-0000-000000000004',
    title: 'Level 2 Wellness & Hair Studios',
    slideType: 'image',
    mediaUrl: '/images/signage/wellness-slide.jpg',
    durationSeconds: 10,
    targetLocations: ['L2_lift', 'L2_escalator'],
    tenantId: null,
    tenant: null,
    headline: 'Recharge on Level 2',
    subheadline: 'Ashi Foot Reflexology • 7 Studio Hair Salon • Skin Labo • Glow Haven',
    isActive: true,
    priority: 4,
  },
  {
    id: 's0000000-0000-0000-0000-000000000005',
    title: 'Wayfinding & Interactive Directory Map',
    slideType: 'html',
    mediaUrl: '/signage/wayfinding-kiosk',
    durationSeconds: 20,
    targetLocations: ['L1_lift', 'L2_lift', 'L3_lift', 'L4_lift', 'L3_ceiling'],
    tenantId: null,
    tenant: null,
    headline: 'Digital Directory & Floor Wayfinding',
    subheadline: 'Touch screen or view full floor layout on your mobile phone',
    isActive: true,
    priority: 5,
  },
];
